// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.9
// source: proto/gophkeeper.proto

package keeperproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data_Type int32

const (
	Data_CREDENTIALS Data_Type = 0
	Data_TEXT        Data_Type = 1
	Data_BINARY      Data_Type = 2
	Data_CARD        Data_Type = 3
)

// Enum value maps for Data_Type.
var (
	Data_Type_name = map[int32]string{
		0: "CREDENTIALS",
		1: "TEXT",
		2: "BINARY",
		3: "CARD",
	}
	Data_Type_value = map[string]int32{
		"CREDENTIALS": 0,
		"TEXT":        1,
		"BINARY":      2,
		"CARD":        3,
	}
)

func (x Data_Type) Enum() *Data_Type {
	p := new(Data_Type)
	*p = x
	return p
}

func (x Data_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Data_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gophkeeper_proto_enumTypes[0].Descriptor()
}

func (Data_Type) Type() protoreflect.EnumType {
	return &file_proto_gophkeeper_proto_enumTypes[0]
}

func (x Data_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Data_Type.Descriptor instead.
func (Data_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{0, 0}
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type    Data_Type `protobuf:"varint,2,opt,name=type,proto3,enum=gophkeeper.Data_Type" json:"type,omitempty"`
	Payload []byte    `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gophkeeper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Data) GetType() Data_Type {
	if x != nil {
		return x.Type
	}
	return Data_CREDENTIALS
}

func (x *Data) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SyncPushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *SyncPushRequest) Reset() {
	*x = SyncPushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gophkeeper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPushRequest) ProtoMessage() {}

func (x *SyncPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPushRequest.ProtoReflect.Descriptor instead.
func (*SyncPushRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *SyncPushRequest) GetData() []*Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type SyncPushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *SyncPushResponse) Reset() {
	*x = SyncPushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gophkeeper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPushResponse) ProtoMessage() {}

func (x *SyncPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPushResponse.ProtoReflect.Descriptor instead.
func (*SyncPushResponse) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *SyncPushResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SyncPullRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
}

func (x *SyncPullRequest) Reset() {
	*x = SyncPullRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gophkeeper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncPullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPullRequest) ProtoMessage() {}

func (x *SyncPullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPullRequest.ProtoReflect.Descriptor instead.
func (*SyncPullRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *SyncPullRequest) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

type SyncPullResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *SyncPullResponse) Reset() {
	*x = SyncPullResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gophkeeper_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncPullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPullResponse) ProtoMessage() {}

func (x *SyncPullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPullResponse.ProtoReflect.Descriptor instead.
func (*SyncPullResponse) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *SyncPullResponse) GetData() []*Data {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_gophkeeper_proto protoreflect.FileDescriptor

var file_proto_gophkeeper_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x22, 0x98, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x29, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x15, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x37, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f,
	0x0a, 0x0b, 0x43, 0x52, 0x45, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x41, 0x4c, 0x53, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x54, 0x45, 0x58, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x49, 0x4e,
	0x41, 0x52, 0x59, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x41, 0x52, 0x44, 0x10, 0x03, 0x22,
	0x37, 0x0a, 0x0f, 0x53, 0x79, 0x6e, 0x63, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x28, 0x0a, 0x10, 0x53, 0x79, 0x6e, 0x63,
	0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x25, 0x0a, 0x0f, 0x53, 0x79, 0x6e, 0x63, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x10, 0x53, 0x79, 0x6e,
	0x63, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x6f,
	0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x32, 0x8c, 0x01, 0x0a, 0x04, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x41, 0x0a, 0x04,
	0x50, 0x75, 0x73, 0x68, 0x12, 0x1b, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x53,
	0x79, 0x6e, 0x63, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x41, 0x0a, 0x04, 0x50, 0x75, 0x6c, 0x6c, 0x12, 0x1b, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x63, 0x64, 0x2f, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_gophkeeper_proto_rawDescOnce sync.Once
	file_proto_gophkeeper_proto_rawDescData = file_proto_gophkeeper_proto_rawDesc
)

func file_proto_gophkeeper_proto_rawDescGZIP() []byte {
	file_proto_gophkeeper_proto_rawDescOnce.Do(func() {
		file_proto_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_gophkeeper_proto_rawDescData)
	})
	return file_proto_gophkeeper_proto_rawDescData
}

var file_proto_gophkeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_gophkeeper_proto_goTypes = []any{
	(Data_Type)(0),           // 0: gophkeeper.Data.Type
	(*Data)(nil),             // 1: gophkeeper.Data
	(*SyncPushRequest)(nil),  // 2: gophkeeper.SyncPushRequest
	(*SyncPushResponse)(nil), // 3: gophkeeper.SyncPushResponse
	(*SyncPullRequest)(nil),  // 4: gophkeeper.SyncPullRequest
	(*SyncPullResponse)(nil), // 5: gophkeeper.SyncPullResponse
}
var file_proto_gophkeeper_proto_depIdxs = []int32{
	0, // 0: gophkeeper.Data.type:type_name -> gophkeeper.Data.Type
	1, // 1: gophkeeper.SyncPushRequest.data:type_name -> gophkeeper.Data
	1, // 2: gophkeeper.SyncPullResponse.data:type_name -> gophkeeper.Data
	2, // 3: gophkeeper.Sync.Push:input_type -> gophkeeper.SyncPushRequest
	4, // 4: gophkeeper.Sync.Pull:input_type -> gophkeeper.SyncPullRequest
	3, // 5: gophkeeper.Sync.Push:output_type -> gophkeeper.SyncPushResponse
	5, // 6: gophkeeper.Sync.Pull:output_type -> gophkeeper.SyncPullResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_gophkeeper_proto_init() }
func file_proto_gophkeeper_proto_init() {
	if File_proto_gophkeeper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_gophkeeper_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gophkeeper_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SyncPushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gophkeeper_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SyncPushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gophkeeper_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SyncPullRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gophkeeper_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SyncPullResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_gophkeeper_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gophkeeper_proto_goTypes,
		DependencyIndexes: file_proto_gophkeeper_proto_depIdxs,
		EnumInfos:         file_proto_gophkeeper_proto_enumTypes,
		MessageInfos:      file_proto_gophkeeper_proto_msgTypes,
	}.Build()
	File_proto_gophkeeper_proto = out.File
	file_proto_gophkeeper_proto_rawDesc = nil
	file_proto_gophkeeper_proto_goTypes = nil
	file_proto_gophkeeper_proto_depIdxs = nil
}
